name: 3d_lift
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - ld_impl_linux-64=2.40
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libnsl=2.0.1
  - libsqlite=3.46.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.0
  - python=3.11.9
  - readline=8.2
  - setuptools=71.0.4
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - addict==2.4.0
      - asttokens==2.4.1
      - attrs==23.2.0
      - blinker==1.8.2
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clip==1.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - dash==2.17.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - flask==3.0.3
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - ftfy==6.2.0
      - huggingface-hub==0.24.2
      - idna==3.7
      - imageio==2.34.2
      - importlib-metadata==8.2.0
      - ipython==8.26.0
      - ipywidgets==8.1.3
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numba==0.60.0
      - numpy==2.0.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - plotly==5.23.0
      - prompt-toolkit==3.0.47
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2024.7.24
      - requests==2.32.3
      - retrying==1.3.4
      - rpds-py==0.19.1
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - six==1.16.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tenacity==8.5.0
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - tokenizers==0.19.1
      - torch==2.4.0
      - torchvision==0.19.0
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.44.0.dev0
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - zipp==3.19.2
